const weatherCodes = {
    0: { description: "Clear sky", },
    1: { description: "Mainly clear" },
    2: { description: "Partly cloudy" },
    3: { description: "Overcast" },
    45: { description: "Fog" },
    48: { description: "Depositing rime fog" },
    51: { description: "Drizzle: Light intensity" },
    53: { description: "Drizzle: Moderate intensity" },
    55: { description: "Drizzle: Dense intensity" },
    56: { description: "Freezing Drizzle: Light intensity" },
    57: { description: "Freezing Drizzle: Dense intensity" },
    61: { description: "Rain: Slight intensity" },
    63: { description: "Rain: Moderate intensity" },
    65: { description: "Rain: Heavy intensity" },
    66: { description: "Freezing Rain: Light intensity" },
    67: { description: "Freezing Rain: Heavy intensity" },
    71: { description: "Snow fall: Slight intensity" },
    73: { description: "Snow fall: Moderate intensity" },
    75: { description: "Snow fall: Heavy intensity" },
    77: { description: "Snow grains" },
    80: { description: "Rain showers: Slight intensity" },
    81: { description: "Rain showers: Moderate intensity" },
    82: { description: "Rain showers: Violent intensity" },
    85: { description: "Snow showers: Slight intensity" },
    86: { description: "Snow showers: Heavy intensity" },
    95: { description: "Thunderstorm: Slight or moderate" },
    96: { description: "Thunderstorm with slight hail" },
    99: { description: "Thunderstorm with heavy hail" }
}